name: "Solicitud de análisis de librería"
description: "Usa este formulario para solicitar un análisis de librería de terceros"
title: "Análisis de librería"
labels: ["análisis"]
body:
  - type: input
    id: correo
    attributes:
      label: "Correo electrónico"
      description: "Ingresa tu correo"
      placeholder: "email@ejemplo.com"
  - type: textarea
    id: descripcion
    attributes:
      label: "Descripción"
      description: "Describe la librería y el motivo del análisis"
      placeholder: "Detalles del análisis"
  - type: input
    id: coordenada
    attributes:
      label: "Coordenada de la librería"
      description: "Ingresa la coordenada de la librería (ej: com.ejemplo:lib:1.0.0)"
      placeholder: "com.ejemplo:lib:1.0.0"
    
